sampleApp:
  meta:
    namespace: default
    minReplicas: 1
    maxReplicas: 10
  image:
    tag: latest
  service:
    type: LoadBalancer
    port: 80
    targetport: 80
  replicas: 8
  resources:
    requests:
      memory: 1
      cpu: 1
    limits:
      memory: 2
      cpu: 3
    targetAverageUtilization: 50
